# -*- coding: utf-8 -*-
"""Update_team.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7FLHgcVzFc-20FbT0kHJih93BfAz_GR
"""

import pandas as pd
import numpy as np
import yaml
import re
import os

data_directory = '_data/'
layout_directory = '_layouts/'

sheet_id = "1GhfX1QMrokc2cWaUUMfuTRBlbEmYqf2gLgEB-oobCBM"
sheet_name = "team"
team_url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
team = pd.read_csv(team_url)
team = team.replace(np.nan, '')

team_roles = [x.split(':')[1] for x in sorted(set(team['role']))]
header_names = team_roles
file_names  = [re.sub(r'[^a-zA-Z]', '', x.lower()) for x in team_roles]

layout = []

temp = '''---
layout: default
description: Template for team page.
---

'''
layout += [temp]

temp = ['{% if page.team and site.data[page.team] %}']
temp += [f"  {{% assign {x} = site.data[page.{x}] %}}" for x in file_names]
temp += ['{% elsif site.data.team %}']
temp += [f"  {{% assign {x} = site.data[page.{x}] %}}" for x in file_names]
temp += ["{% endif %}"]
layout += temp

code_snippet = '''<div class="col-md-4 col-lg-3 col-sm-6 team-member">
    <div class="member-container" style="text-align: center;">
      <div class="flex-shrink-0 mx-auto">
        {% if member.image %}
          <img src="{{ member.image | relative_url }}" alt="{{ member.name }} " class="img-fluid">
        {% endif %}
      </div>
      <div>
        {% if member.website %}
          <a href="{{ member.website }}">
            <h5 id="{{ member.name | strip | url_encode }}">
              {{ member.name }}
              {% if member.role %}
                <small class="text-muted">| {{ member.role }}</small>
              {% endif %}
            </h5>
          </a>
        {% else %}
          <h5 id="{{ member.name | strip | url_encode }}">
            {{ member.name }}
            {% if member.role %}
              <small class="text-muted">| {{ member.role }}</small>
            {% endif %}
          </h5>
        {% endif %}

        {{ member.description | markdownify }}

        <ul class="list-inline">
          {% if member.email %}
            <li class="list-inline-item">
              <a href="mailto:{{ member.email }}"><i class="far fa-envelope"></i></a>
            </li>
          {% endif %}

          {% if member.orcid %}
            <li class="list-inline-item">
              <a href="https://orcid.org/{{ member.orcid }}"><i class="ai ai-orcid"></i></a>
            </li>
          {% endif %}

          {% if member.researchgate %}
            <li class="list-inline-item">
              <a href="https://researchgate.net/profile/{{ member.researchgate }}"><i class="ai ai-researchgate"></i></a>
            </li>
          {% endif %}

          {% if member.googlescholar %}
            <li class="list-inline-item">
              <a href="https://scholar.google.com/citations?user={{ member.googlescholar }}"><i class="ai ai-google-scholar"></i></a>
            </li>
          {% endif %}

          {% if member.twitter %}
            <li class="list-inline-item">
              <a href="https://twitter.com/{{ member.twitter }}"><i class="fab fa-twitter"></i></a>
            </li>
          {% endif %}

          {% if member.youtube %}
            <li class="list-inline-item">
              <a href="https://www.youtube.com/c/{{ member.youtube }}"><i class="fab fa-youtube"></i></a>
            </li>
          {% endif %}

          {% if member.mastodon %}
            <li class="list-inline-item">
              <a href="{{ member.mastodon }}"><i class="fab fa-mastodon"></i></a>
            </li>
          {% endif %}

          {% if member.github %}
            <li class="list-inline-item">
              <a href="https://github.com/{{ member.github }}"><i class="fab fa-github"></i></a>
            </li>
          {% endif %}

          {% if member.linkedin %}
            <li class="list-inline-item">
              <a href="https://www.linkedin.com/in/{{ member.linkedin }}"><i class="fab fa-linkedin"></i></a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
{% endfor %}'''

temp = []
for header_name, file_name in zip(header_names, file_names):
  temp += [f'\n<h2>{header_name}</h2>\n']
  temp += [f"{{% for member in {file_name} %}}"]
  temp += [code_snippet]
layout += temp

if os.path.exists(os.path.join(layout_directory, 'team.html')):
  os.remove(os.path.join(layout_directory, 'team.html'))
with open(os.path.join(layout_directory, 'team.html'), 'w') as f:
  f.write('\n'.join(layout))

for header_name, file_name in zip(header_names, file_names):
  df = team[team['role']==header_name]
  data = df.to_dict(orient='records')
  filtered_data = [{k: v for k, v in row.items() if v != ''} for row in data]
  yaml_output = yaml.dump(filtered_data, default_flow_style=False, allow_unicode=True)
  if os.path.exists(os.path.join(data_directory, f'{file_name}.yml')):
    os.remove(os.path.join(data_directory, f'{file_name}.yml'))
  with open(os.path.join(data_directory, f'{file_name}.yml'), 'w') as f:
    f.write(yaml_output)
