name: test data up
on:
  schedule: 
    - cron: "*/6 * * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echoing something
        run: echo "🎉 The job was automatically triggered"
