name: test data up
on:
  schedule: 
    - cron: "*/6 * * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: install dependancies
        run: | 
          echo ""::debug::let me tell you something"
          pip install pyyaml pandas
      - name: Run python file
        run: |
          echo ""::debug::let me tell you something, let me tell you something"
          python update_data.py
      - name: Commit and push changes
        run: |
          echo ""::debug::let me tell you something, let me tell you something, let me tell you something"
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "add"
          echo ${{ secrets.REPO_TOKEN }}
          git add .
          git commit -m "Update data"
          git push origin main
          


